name: Pull Request Checks

on:
  pull_request:
    branches:
      - main

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Install dependencies
        run: npm install

      - name: Check for conventional commit messages
        uses: wagoid/commitlint-github-action@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          configFile: './commitlint.config.js'
      
      - name: Lint project
        run: npm run lint

      - name: Build project
        run: npm run build

      - name: Run tests
        run: npm run test
